### ISSUE TITLE
[Hunts] Rare Hunt Requirement Cutoff

### ISSUE THREAD

**Issue by Khrisstias** [ObliqueNetwork/Terra#1900]
**Describe the bug**
When hovering the mouse over the rare hunt for the requirements, the nature list is so long I cannot see what gender of the Pokémon I need to catch.

**To Reproduce**
1. execute /hunts
2. hover the mouse over the rare hunt

**Expected behavior**
I should be able to see the required gender

**Screenshots**
![2022-09-28_17 27 52](https://user-images.githubusercontent.com/37944220/192900124-9caaf84f-563b-42fe-9f59-bdd5332034b6.png)

**Username:** DraconiacLatias

**Server name (all applicable):** Orion, very likely all

**Comment by StrideMate** [comment]
Hello fellow, Executive hehe! I've checked this on Orion and it seems to have been solved, If it occurs in the future reopen this tickets! <3 Closing! (P.S I also do think this can have something to do with the GUI scale thing, So just keep that in mind!)

![2023-01-27_00 14 30](https://user-images.githubusercontent.com/78794976/214844825-20255582-01d7-4509-b49d-c8d0ebde7f87.png)

**Comment by Deathnight7976** [comment]
This is still an issue for those who use larger GUI's possible solutions may include adjusting Rare hunts to be slightly harder by removing a few possible natures to make the list shorter or listing multiple natures per line.

**Comment by KittyKatzyn** [comment]
Confirmed, still an issue on larger GUI settings.  Needs to be migrated!

**Comment by KittyKatzyn** [comment]
Forwarded to Internal tracker! Will update here when fixed!
