### ISSUE TITLE
Unable to use items on Pokemon in Vanha

### ISSUE THREAD

**Issue by CaptainTCovenant** [ObliqueNetwork/Terra#1980]
**Describe the bug**
Can't use items on a Pokemon in Vanha on Orion and Atlas server; works fine in Titan 

**To Reproduce**
1. Go to any town - Tesla is where I tested at
2. Try rightclicking a Pokemon with Ras' Golden Lens 
3. See error

**Expected behavior**
'You don't have an administrator's permission to use "item" 

![Screenshot_402](https://user-images.githubusercontent.com/92965754/202066203-86481854-687a-440e-9277-df743a206578.png)

**Server name (all applicable):**
Orion , Atlas

**Comment by StrideMate** [comment]
I've tested this on both Orion and Atlas, I couldn't recreate it, So I believe this issue is fixed! If it occurs in the future please let us know! Closing!

**Comment by Deathnight7976** [comment]
This is still an issue, Stride just forgot he simply ignores admin claims.

**Comment by Chunkkss** [comment]
Fixed.
