### ISSUE TITLE
[Beast Rank] Showing colour code on tab

### ISSUE THREAD

**Issue by chefburnt** [ObliqueNetwork/Terra#2085]
When you press tab in-game, if someone is Beast rank, their tag will show up incorrectly, displaying the colour code at the end.

1. Join Atlas, Orion or Titan
2. Press tab
3. If someone is Beast rank, you will see the error. 

![2023-01-23_18 27 28](https://user-images.githubusercontent.com/123426993/214189070-61aed159-d78d-48e9-adb4-b74eb75ae04b.png)

Issue is on all 3 servers

**Comment by Rasgnarok** [comment]
Fixed

**Comment by Chunkkss** [comment]
Reopening this, still showing the color code on all servers for beast rank in tab menu.

**Comment by Deathnight7976** [comment]
This has been resolved.
